# Generated by Django 5.2.1 on 2025-06-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='product_content_type',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='product_object_id',
        ),
    ]
