# Generated by Django 5.2.1 on 2025-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
