# Generated by Django 5.2.1 on 2025-06-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_discountproduct_discount_percentage'),
        ('products', '0004_freeproduct'),
    ]

    operations = [
    ]
