# Generated by Django 5.2.1 on 2025-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discountproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='original_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
