# Generated by Django 5.2.1 on 2025-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Fulfilled', 'Fulfilled')], default='Active', max_length=20),
        ),
    ]
