# Generated by Django 5.2.2 on 2025-06-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token_created_at',
        ),
    ]
