# Generated by Django 5.2.3 on 2025-06-15 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_items_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_items_shared',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReputationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('item_shared', 'Item Shared'), ('item_received', 'Item Received'), ('transaction_completed', 'Transaction Completed'), ('positive_feedback', 'Positive Feedback'), ('negative_feedback', 'Negative Feedback'), ('profile_completed', 'Profile Completed'), ('first_listing', 'First Listing'), ('community_interaction', 'Community Interaction')], max_length=30)),
                ('points_earned', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_item_id', models.IntegerField(blank=True, null=True)),
                ('related_item_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
